export const LOCAL_CITY_REQUESTED = 'LOCAL_CITY_REQUESTED';
export const LOCAL_CITY_SUCCEEDED = 'LOCAL_CITY_SUCCEEDED';

export const WEATHER_REQUESTED = 'WEATHER_REQUESTED';
export const WEATHER_SUCCEEDED = 'WEATHER_SUCCEEDED';

export const FORECAST_REQUESTED = 'FORECAST_REQUEST';
export const FORECAST_SUCCEEDED = 'FORECAST_SUCCEEDED';

export const SET_ERROR = 'SET_ERROR';
